### ISSUE TITLE
Move game notifications so they don't interfere with clock

### ISSUE THREAD

**Issue by valitas** [valitas/Pardus-Sweetener#41]
From Vasha:

Standard game notifications like missions finished should be moved a little to the left, because they're interfering with clock

**Comment by Blackwaylander** [comment]
yep, clock is nearly unreadable, any ideas on how to move either

**Comment by Blackwaylander** [comment]
Doh, if you read them they disappear, blush's

**Comment by valitas** [comment]
Just cleaning the issue liest. This one is old and won't be implemented, as the issue doesn't prevent use and changing the current layout would probably just make things ugly.
