### ISSUE TITLE
Functionality based on GM script "Pardus_Pathfinder"

### ISSUE THREAD

**Issue by dsshad** [valitas/Pardus-Sweetener#66]
Another request:

Functionality based on GM script "Pardus_Pathfinder". It makes a colored border around the tile one is currently at and displays the path one will take, if one clicks the destination tile directly.

Here the screenshot displaying it + the grid lines I've mentioned in the other request:

![grafik](https://user-images.githubusercontent.com/43317663/45598029-56c93680-b9d5-11e8-93fd-4e7859d65266.png)

[pardus_pathfinder.zip](https://github.com/valitas/Pardus-Sweetener/files/2386727/pardus_pathfinder.zip)

**Comment by BartKieviet** [comment]
This is already implemented

**Comment by dsshad** [comment]
Ok, your are right. Looks a bit differently, but it's implemented indeed. Must have missed (or forgott) about it.
